language: go

go:
 - 1.4

before_install:
  - zip=`curl -vs https://storage.googleapis.com/appengine-sdks/ 2>&1 | sed -e 's/</\'$'\n</g' | grep featured/google_appengine | sed -e 's/<Key>//' | sort | tail -1`
  - curl -o $HOME/google_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/$zip
  - unzip -q -d -v $HOME $HOME/google_appengine.zip

install:
 - go get -v github.com/rchargel/gohuman

script:
 - go test -v -bench=. github.com/rchargel/gohuman
