language: go

go:
 - 1.4

before_install:
 - export FILE=$(curl https://storage.googleapis.com/appengine-sdks/ | grep -oP '(?<=featured/)go_appengine_sdk_linux_amd64-[^\<]*' | head -1)
 - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
 - unzip -v $FILE

install:
 - go get -v github.com/rchargel/gohuman

script:
 - ./go_appengine/goapp test -v -bench=. github.com/rchargel/gohuman
