language: go

go:
 - 1.2.1
 - 1.3
 - 1.4

install:
 - go get -v github.com/rchargel/gohuman

script:
 - go test -v -coverprofile=c.out -bench=. github.com/rchargel/gohuman
 - go tool cover -func=c.out
